DELETE http://localhost:4040/events/1/register
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NTg3NzMyNDcsInVzZXJJZCI6MX0.4_BBcrhfmsaiT13aYiOEa4a9_9a9INOu_-Hm0Bht-Cg