POST http://localhost:4040/events
Content-Type: application/json

{
    "name": "Sample Event 2",
    "description": "This is a sample event description.",
    "location": "Sample Location",
    "dateTime": "2024-12-31T20:00:00Z",
    "userId": 1
}